import type { Metadata } from "next";

import "./globals.css";

import { Wallet } from "./component/Wallet";
import  Homepage  from "./component/HomePage";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Wallet>
					<Homepage />
					{children}
				</Wallet>
			</body>
		</html>
	);
}
